# Generated by Django 4.2 on 2024-02-17 15:39

import django.core.validators
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOriginalImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('csv_file', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('original_image', models.TextField(blank=True, max_length=100)),
                ('original_width', models.IntegerField(blank=True, null=True)),
                ('original_height', models.IntegerField(blank=True, null=True)),
                ('resized_image', models.TextField(blank=True, max_length=100)),
                ('resized_width', models.IntegerField(blank=True, null=True)),
                ('resized_height', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('minimum_depth', models.IntegerField(blank=True, null=True)),
                ('maximum_depth', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical original image',
                'verbose_name_plural': 'historical original images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReConstructImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reconstruct_image', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical re construct image',
                'verbose_name_plural': 'historical re construct images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('csv_file', models.FileField(upload_to='csv_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('original_image', models.ImageField(blank=True, upload_to='original_images/')),
                ('original_width', models.IntegerField(blank=True, null=True)),
                ('original_height', models.IntegerField(blank=True, null=True)),
                ('resized_image', models.ImageField(blank=True, upload_to='resized_image/')),
                ('resized_width', models.IntegerField(blank=True, null=True)),
                ('resized_height', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('minimum_depth', models.IntegerField(blank=True, null=True)),
                ('maximum_depth', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReConstructImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('reconstruct_image', models.ImageField(upload_to='reconstruct_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
