# Generated by Django 4.2 on 2024-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_builder', '0002_reconstructimage_created_reconstructimage_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreconstructimage',
            old_name='resized_image',
            new_name='reconstruct_image',
        ),
        migrations.RenameField(
            model_name='reconstructimage',
            old_name='resized_image',
            new_name='reconstruct_image',
        ),
        migrations.RemoveField(
            model_name='historicalreconstructimage',
            name='resized_height',
        ),
        migrations.RemoveField(
            model_name='historicalreconstructimage',
            name='resized_width',
        ),
        migrations.RemoveField(
            model_name='reconstructimage',
            name='resized_height',
        ),
        migrations.RemoveField(
            model_name='reconstructimage',
            name='resized_width',
        ),
        migrations.AddField(
            model_name='historicaloriginalimage',
            name='maximum_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloriginalimage',
            name='minimum_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloriginalimage',
            name='resized_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloriginalimage',
            name='resized_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='maximum_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='minimum_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='resized_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='resized_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloriginalimage',
            name='original_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloriginalimage',
            name='original_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
