# Generated by Django 4.2 on 2024-02-16 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_builder', '0003_rename_resized_image_historicalreconstructimage_reconstruct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloriginalimage',
            name='csv_file',
            field=models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='csv_file',
            field=models.FileField(upload_to='csv_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
