# Generated by Django 4.2 on 2024-02-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_builder', '0004_alter_historicaloriginalimage_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloriginalimage',
            name='resized_image',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='resized_image',
            field=models.ImageField(blank=True, upload_to='resized_image/'),
        ),
    ]
