# Generated by Django 4.2 on 2024-02-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_builder', '0005_historicaloriginalimage_resized_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconstructimage',
            name='reconstruct_image',
            field=models.ImageField(upload_to='reconstruct_images/'),
        ),
    ]
